In [1]:
a = [i for i in range(100000)]
b = [i for i in range(100000,200000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time() - start)


0.009528160095214844


In [1]:
import numpy as np

In [22]:
a = np.arange(24).reshape(6,4)

In [23]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [27]:
a[3:7,1:3][1:3]

array([[17, 18],
       [21, 22]])

In [26]:
a[3:7,1:3][1:3]

array([[17, 18],
       [21, 22]])

In [9]:
a[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [34]:
a = np.random.randint(1,100,24).reshape(6,4)

In [43]:
a[a>90]

array([96, 97])

In [44]:
a

array([[96, 21, 41, 45],
       [16, 87, 64, 66],
       [64,  1, 16,  6],
       [71, 97, 72, 73],
       [20, 69, 63, 51],
       [80, 26, 16, 59]])

In [46]:
a[a%2==0]

array([96, 16, 64, 66, 64, 16,  6, 72, 20, 80, 26, 16])

In [47]:
a[a%2!=0]

array([21, 41, 45, 87,  1, 71, 97, 73, 69, 63, 51, 59])

In [49]:
a[(a>50) & (a%2!=0)]

array([87, 71, 97, 73, 69, 63, 51, 59])

In [51]:
a[(a>50) & (a%2==0)]

array([96, 64, 66, 64, 72, 80])

In [52]:
a[a%7==0]

array([21, 63])

In [53]:
a[~(a%7==0)]

array([96, 41, 45, 16, 87, 64, 66, 64,  1, 16,  6, 71, 97, 72, 73, 20, 69,
       51, 80, 26, 16, 59])

In [54]:
a[(a%7!=0)]

array([96, 41, 45, 16, 87, 64, 66, 64,  1, 16,  6, 71, 97, 72, 73, 20, 69,
       51, 80, 26, 16, 59])