In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


Creating Numpy array


In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
a = [1,2,3]
print(a)

[1, 2, 3]


#Matrics di - 2 rows and 3 columns


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
b = np.array([[1,2,3,8],[4,5,6,9]])
print(b)

[[1 2 3 8]
 [4 5 6 9]]


In [14]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [17]:
k = [i for i in range(1,10,2)]
print(k)

[1, 3, 5, 7, 9]


In [19]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [29]:
np.arange(16).reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [32]:
np.ones((4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.random.random((5,10))

array([[0.5484688 , 0.78522881, 0.65426539, 0.68092539, 0.91675357,
        0.60372247, 0.219384  , 0.71116387, 0.08995414, 0.33142326],
       [0.41172644, 0.0169005 , 0.0327231 , 0.91849346, 0.20948619,
        0.08264879, 0.03399939, 0.82066932, 0.339618  , 0.85519509],
       [0.12127321, 0.39870522, 0.9226958 , 0.30574881, 0.34270277,
        0.38618499, 0.44125011, 0.48643119, 0.99538273, 0.60014814],
       [0.90561721, 0.37529789, 0.43800867, 0.32468899, 0.4412909 ,
        0.35996302, 0.96015302, 0.38793191, 0.7795083 , 0.9002595 ],
       [0.71328179, 0.10068718, 0.55141028, 0.47518401, 0.97790125,
        0.51797386, 0.59406877, 0.90956118, 0.96023004, 0.77195153]])

In [41]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
a1= np.arange(10,dtype=np.int64).reshape(10,1)

In [84]:
a1.astype(np.float64)

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]])

In [72]:
print(a1)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [83]:
a1.itemsize

8

In [64]:
a1.ndim

2

In [66]:
a3 = np.arange(8).reshape(2,2,2)

In [67]:
a3.ndim

3

In [68]:
a3.shape

(2, 2, 2)

In [69]:
a3.size

8

In [101]:
a1 = np.arange(16).reshape(4,4)

In [97]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [100]:
np.linalg.inv([[1,2],[3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [90]:
a1 * 2 + a1 * 2

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [91]:
a1 * 2 * a1 * 2

array([[  0,   4,  16,  36],
       [ 64, 100, 144, 196],
       [256, 324, 400, 484]])

### Array Function


In [10]:
a1 = np.random.random((3,3))
a1 = a1 * 100

In [11]:
a1

array([[21.84113086, 17.06538045,  2.23396177],
       [83.50780203, 49.78536442, 97.59564451],
       [13.97507905, 53.94855   ,  8.79333001]])

In [12]:
a1 = np.round(a1)
a1

array([[22., 17.,  2.],
       [84., 50., 98.],
       [14., 54.,  9.]])

In [14]:
np.prod(a1,axis = 0)

array([25872., 45900.,  1764.])

In [15]:
np.prod(a1,axis = 1)

array([   748., 411600.,   6804.])

In [16]:
np.std(a1)

32.521597761912844

In [17]:
np.std(a1,axis=0)

array([31.28364855, 16.57977349, 43.69846171])

In [18]:
np.std(a1,axis=1)

array([ 8.49836586, 20.15495528, 20.13840996])

In [19]:
np.mean(a1)

38.888888888888886

In [20]:
np.mean(a1,axis=0)

array([40.        , 40.33333333, 36.33333333])

In [21]:
np.mean(a1,axis=1)

array([13.66666667, 77.33333333, 25.66666667])

In [23]:
a1

array([[22., 17.,  2.],
       [84., 50., 98.],
       [14., 54.,  9.]])

In [22]:
np.sin(a1)

array([[-0.00885131, -0.96139749,  0.90929743],
       [ 0.73319032, -0.26237485, -0.57338187],
       [ 0.99060736, -0.55878905,  0.41211849]])

In [25]:
np.cos(a1)

array([[-0.99996083, -0.27516334, -0.41614684],
       [-0.6800235 ,  0.96496603, -0.81928825],
       [ 0.13673722, -0.82930983, -0.91113026]])

In [42]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(3,4)

In [38]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [40]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [43]:
a2 * a3

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [44]:
np.log(a1)

array([[3.09104245, 2.83321334, 0.69314718],
       [4.4308168 , 3.91202301, 4.58496748],
       [2.63905733, 3.98898405, 2.19722458]])

In [46]:
a1

array([[22., 17.,  2.],
       [84., 50., 98.],
       [14., 54.,  9.]])

In [45]:
np.exp(a1)

array([[3.58491285e+09, 2.41549528e+07, 7.38905610e+00],
       [3.02507732e+36, 5.18470553e+21, 3.63797095e+42],
       [1.20260428e+06, 2.83075330e+23, 8.10308393e+03]])

Indexing and Slicing


In [48]:
a1 = np.arange(10)
a2 =np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [49]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a1[-3:]

array([7, 8, 9])

In [59]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a2[1,3]

7

In [68]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
a3[1,1,1]

7

In [77]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a1[2:5:2]

array([2, 4])

In [79]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
a2[0:4,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])