In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


Creating Numpy array


In [6]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
a = [1,2,3]
print(a)

[1, 2, 3]


#Matrics di - 2 rows and 3 columns


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
b = np.array([[1,2,3,8],[4,5,6,9]])
print(b)

[[1 2 3 8]
 [4 5 6 9]]


In [14]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [17]:
k = [i for i in range(1,10,2)]
print(k)

[1, 3, 5, 7, 9]


In [19]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [29]:
np.arange(16).reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [32]:
np.ones((4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.random.random((5,10))

array([[0.5484688 , 0.78522881, 0.65426539, 0.68092539, 0.91675357,
        0.60372247, 0.219384  , 0.71116387, 0.08995414, 0.33142326],
       [0.41172644, 0.0169005 , 0.0327231 , 0.91849346, 0.20948619,
        0.08264879, 0.03399939, 0.82066932, 0.339618  , 0.85519509],
       [0.12127321, 0.39870522, 0.9226958 , 0.30574881, 0.34270277,
        0.38618499, 0.44125011, 0.48643119, 0.99538273, 0.60014814],
       [0.90561721, 0.37529789, 0.43800867, 0.32468899, 0.4412909 ,
        0.35996302, 0.96015302, 0.38793191, 0.7795083 , 0.9002595 ],
       [0.71328179, 0.10068718, 0.55141028, 0.47518401, 0.97790125,
        0.51797386, 0.59406877, 0.90956118, 0.96023004, 0.77195153]])

In [41]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
a1= np.arange(10,dtype=np.int64).reshape(10,1)

In [84]:
a1.astype(np.float64)

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]])

In [72]:
print(a1)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [83]:
a1.itemsize

8

In [64]:
a1.ndim

2

In [66]:
a3 = np.arange(8).reshape(2,2,2)

In [67]:
a3.ndim

3

In [68]:
a3.shape

(2, 2, 2)

In [69]:
a3.size

8

In [101]:
a1 = np.arange(16).reshape(4,4)

In [97]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [100]:
np.linalg.inv([[1,2],[3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [90]:
a1 * 2 + a1 * 2

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [91]:
a1 * 2 * a1 * 2

array([[  0,   4,  16,  36],
       [ 64, 100, 144, 196],
       [256, 324, 400, 484]])